name: CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Pull Repo
      - uses: actions/checkout@v3

      # Github Secrets에서 API Key 받아온 후 .env 파일에 추가
      - run: |
          echo "REACT_APP_API_KEY=${{secrets.REACT_APP_API_KEY}}" >> .env
          echo "REACT_APP_AUTH_DOMAIN=${{secrets.REACT_APP_AUTH_DOMAIN}}" >> .env
          echo "REACT_APP_PROJECT_ID=${{secrets.REACT_APP_PROJECT_ID}}" >> .env
          echo "REACT_APP_STORAGE_BUCKET=${{secrets.REACT_APP_STORAGE_BUCKET}}" >> .env
          echo "REACT_APP_MESSAGING_SENDER_ID=${{secrets.REACT_APP_MESSAGING_SENDER_ID}}" >> .env
          echo "REACT_APP_API_ID=${{secrets.REACT_APP_API_ID}}" >> .env
          echo "REACT_APP_MEASUREMNT_ID=${{secrets.REACT_APP_MEASUREMNT_ID}}" >> .env
      - run: cat .env

      - run: npm install
      - run: npm run build
